export const BOARD_LIST='BOARD_LIST'
export const BOARD_PAGE='BOARD_LIST'
export const BOARD_DETAIL='BOARD_DETAIL'

export const BOARD_UPDATE_DATA='BOARD_UPDATE_DATA'
export const BOARD_INSERT='BOARD_INSERT'
export const BOARD_UPDATE='BOARD_UPDATE'
export const BOARD_DELETE='BOARD_DELETE'