export const BOARD_LIST='BOARD_LIST'
export const BOARD_PAGE='BOARD_PAGE'
export const BOARD_DETAIL='BOARD_DETAIL'

export const BOARD_UPDATE_DATA='BOARD_UPDATE_DATA'
export const BOARD_INSERT='BOARD_INSERT'
export const BOARD_UPDATE='BOARD_UPDATE'
export const BOARD_DELETE='BOARD_DELETE'

export const BOARD_MAIN_LIST='BOARD_MAIN_LIST'
export const BOOK_MAIN_LIST='BOOK_MAIN_LIST'


export const BOOK_LIST='BOOK_LIST'
export const BOOK_DETAIL='BOOK_DETAIL'